### PR TITLE
#20: Adds build-args to Github Actions

### LINKED ISSUE #20: Add build-args to Github Actions
As shown in the error here https://github.com/lspcontainers/dockerfiles/runs/2562902350 we are not providing `build-args` to jobs in Github Actions.

### PR DESCRIPTION
**Pull request by erkrnt**
Closes #20

### CODE REVIEW

**Review by darthmeme — APPROVED** [review]
BG SQUEEGEE APPROVED

**Comment by natsirtremraf** [comment]
Looks Cool To me!

**Comment by nogweii** [comment]
LGTM :shipit:

**Comment by medoix** [comment]
LGTM

**Pull request merged**
