### PR TITLE
feature: adding json ls

### PR DESCRIPTION
**Pull request by dbgeek**
Hope I got the naming correct

### CODE REVIEW

**Comment by nogweii** [comment]
@dbgeek the naming is fine, but I wonder if we should remove the leading "vscode-" from the container name. It's not wrong, to be clear, but I feel like it's a tad redundant / ugly.

**Comment by dbgeek** [comment]
> @dbgeek the naming is fine, but I wonder if we should remove the leading "vscode-" from the container name. It's not wrong, to be clear, but I feel like it's a tad redundant / ugly.

Agree, will remove it.

**Comment by dbgeek** [comment]
maybe is **json-language-server** a better name

**Review by nogweii — DISMISSED** [review]
I like that name! 👍

**Review by erkrnt — DISMISSED** [review]
LGTM

**Review by nogweii — APPROVED** [review]
merge fix worked, nice

**Pull request merged**
