### PR TITLE
feature: terraformls 0.17

### PR DESCRIPTION
**Pull request by dbgeek**
bumping terraformls to 0.17.0

### CODE REVIEW

**Review by nogweii — COMMENTED** [review]
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwff

**Review by nogweii — APPROVED** [review]

**Comment by nogweii** [comment]
@dbgeek btw, in the mean time, [0.17.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.17.1) was released. Mind updated this PR, or making a new one?

**Comment by erkrnt** [comment]
Going to merge this for now - we can open up a PR for a new bump later.

**Review by erkrnt — APPROVED** [review]
LGTM

**Pull request merged**
