### PR TITLE
add latest tag to CI builds

### PR DESCRIPTION
**Pull request by nogweii**
This is a floating tag that points to the latest build of the container from CI.

### CODE REVIEW

**Comment by nogweii** [comment]
We aren't solving the new-version problem, with this PR anymore. Instead, the solution will be a command in the editor plugins to force a fresh pull

**Comment by nogweii** [comment]
@dbgeek want to make sure you saw this has changed after you gave your thumbs-up

**Review by erkrnt — APPROVED** [review]
LGTM

**Review by erkrnt — APPROVED** [review]
LGTM - again.

**Pull request merged**
