### PR TITLE
Add jedi-language-server (a Python LSP)

### PR DESCRIPTION
**Pull request by WhyNotHugo**
I've been using this for a while, works fine.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Actually, this has some issues.

`jedi_language_server` expects the current project's dependencies to be installed in its same environment. Because those are not inside the container, completion and other features work rather poorly.

**Comment by jgero** [comment]
Hey, I think the Go language server works like this aswell. I already created a PR in lspcontainers/lspcontainers.nvim#33 to make it work in Go. For this language server you cold probably make it work in a similar way.

**Comment by WhyNotHugo** [comment]
Smart. I don't think the same approach can work with Python though. For a few reasons:

1. There's no single place where all dependencies get downloaded.
2. It's hard to figure out _how_ to find the virtualenv with the dependencies. The project might be using `poetry` `flit` or `pipenv` or `mkvirtualenv` to handle dependencies, and it's non-trivial to find out which.

Regarding (2), I'm working on a wrapper that figures that out for other dev tools, so it might be usable here somehow. The problem is this needs to run in the host, since the tool being used indicates where the virtualenv is located.

**Comment by AnkitSiva** [comment]
Maybe a potential workaround for this is to create a custom image with the requirements is installed in a project specific LSP container? This breaks the independence of the language server and the project, but helps with also supporting cases where someone is developing in a container too. I suppose this is a larger solution than for just this PR but putting it out there.

**Comment by erkrnt** [comment]
> 
> 
> Actually, this has some issues.
> 
> `jedi_language_server` expects the current project's dependencies to be installed in its same environment. Because those are not inside the container, completion and other features work rather poorly.

Sorry for my delayed reply - been working and moving which has consumed a lot of my time. This is indeed how `gopls` currently works due to how packages are resolved in the container and mounting the host packages into the container is a possible option.

**Comment by erkrnt** [comment]
> 
> 
> Smart. I don't think the same approach can work with Python though. For a few reasons:
> 
>     1. There's no single place where all dependencies get downloaded.
> 
>     2. It's hard to figure out _how_ to find the virtualenv with the dependencies. The project might be using `poetry` `flit` or `pipenv` or `mkvirtualenv` to handle dependencies, and it's non-trivial to find out which.
> 
> 
> Regarding (2), I'm working on a wrapper that figures that out for other dev tools, so it might be usable here somehow. The problem is this needs to run in the host, since the tool being used indicates where the virtualenv is located.

I'm thinking the problem here is essentially the approach to package management with something like `virtalenv` over `npm`. For example, `virtualenv` hijacks the shell itself to work properly where as something like `npm` is just a file path. Because `virtualenv` is dependent on a shell - it may be a requirement (though I don't know the solution) in order to resolve the packages.

If I think about this a bit more - it seems you'd need some way to essentially reproduce the steps taken to create a virtual environment in the container and then run some kind of automation script to install everything on start...

OR

Don't use virtualenv at all and find a different approach for this.

If you think about it - `virtualenv` is doing the exact same thing that our container is doing so in a way it's just an added layer. Might find it easier to avoid any of it and just install the packages to the system somehow.

**Comment by WhyNotHugo** [comment]
> For example, virtualenv hijacks the shell itself to work properly where as something like npm is just a file path.

Raw-virtualenv just alters your `$PATH` and adds `/path/to/virtualenv/bin` to it.

However, virtualenv is rarely used directly, it's usually used by a higher level tool, like `mkvirtualenv`, `poetry` or `pipenv`. Each of these tools store the generated `virtualenv` in a different location too.

And that's where the tricky part comes...

> Might find it easier to avoid any of it and just install the packages to the system somehow.

If the project uses `poetry`, then dependencies are defined in `pyproject.toml` with one format. If the project uses `pipenv`,then it's a different file. Finally, the project might be using neither, at which point you have to guess if it's in `setup.py` or `requirements.txt`.

Until the Python ecosystem as a whole has converged into "one way to defined dependencies" a bit more, I don't think there's much that can be done here.

It would be possible to write a script to determine the right thing, and build a container on-the-fly, but this is rather tricky:

- When does the images get rebuilt? E.g.: How do we pick up dependency changes?
- Do we pile up a new container for each python project that's opened?
- Is the user responsible for cleaning up stale images?

I'm starting to think that this particular LSP is ill-suited to be containerised; mostly due to bigger inconsistencies in python-land itself.

**Comment by jgero** [comment]
> Smart. I don't think the same approach can work with Python though. For a few reasons:
> 
>     1. There's no single place where all dependencies get downloaded.
> 
>     2. It's hard to figure out _how_ to find the virtualenv with the dependencies. The project might be using `poetry` `flit` or `pipenv` or `mkvirtualenv` to handle dependencies, and it's non-trivial to find out which.
> 
> 
> Regarding (2), I'm working on a wrapper that figures that out for other dev tools, so it might be usable here somehow. The problem is this needs to run in the host, since the tool being used indicates where the virtualenv is located.

Could it be an option to off-load this to the lspcontainers config? Maybe we could add an option there to specify a path where the dependencies are located and then mount that path into the container. I get that this is not a very pretty option either because if you may need to have different configs for different projects, but this way we at least could avoid building extra tools for finding dependencies.

**Comment by WhyNotHugo** [comment]
> Maybe we could add an option there to specify a path where the dependencies are located and then mount that path into the container.

- Poetry uses `{cache-dir}/virtualenvs`, or `$POETRY_VIRTUALENVS_PATH`.
- Pipenv uses `$WORKON_HOME`.
- mkvirtualenv uses `$WORKON_HOME`.
- There are other tools (e.g.: `flit`), so this list is non-exhaustive.

We'd need some logic on the host to determine which of these is used, and mount the right thing.

As an alternative, we can simply mount _all_ of the above as read-only volumes, and let the tools inside the container figure out which one they need.

This however, only covers the "find the right virtualenv location" part, and not actually running the tools inside them.

---

I'm currently working on a small python script to help with something very related. `mypy` is a type-checking tool for Python, that has to run inside the virtualenv (since it needs to access all the project dependencies).

I run this via a non-containerised LSP, but an issue I have is that I need to activate the virtualenv _before_ I run vim (so that the `mypy` inside the virtualenv is run, and _not_ the `mypy` in `/usr/bin`. The wrapper script I'm working on detects which of the above (poetry/pipenv/mkvirtualenv) a project uses, and runs the `mypy` inside of that virtualenv.

I feel that this might be a useful piece in the puzzle we're trying to build here, but containerising on top of it is an extra step.

**Comment by WhyNotHugo** [comment]
> Maybe we could add an option there to specify a path where the dependencies are located and then mount that path into the container.

- Poetry uses `{cache-dir}/virtualenvs`, or `$POETRY_VIRTUALENVS_PATH`.
- Pipenv uses `$WORKON_HOME`.
- mkvirtualenv uses `$WORKON_HOME`.
- There are other tools (e.g.: `flit`), so this list is non-exhaustive.

We'd need some logic on the host to determine which of these is used, and mount the right thing.

As an alternative, we can simply mount _all_ of the above as read-only volumes, and let the tools inside the container figure out which one they need.

This however, only covers the "find the right virtualenv location" part, and not actually running the tools inside them.

---

I'm currently working on a small python script to help with something very related. `mypy` is a type-checking tool for Python, that has to run inside the virtualenv (since it needs to access all the project dependencies).

I run this via a non-containerised LSP, but an issue I have is that I need to activate the virtualenv _before_ I run vim (so that the `mypy` inside the virtualenv is run, and _not_ the `mypy` in `/usr/bin`. The wrapper script I'm working on detects which of the above (poetry/pipenv/mkvirtualenv) a project uses, and runs the `mypy` inside of that virtualenv.

I feel that this might be a useful piece in the puzzle we're trying to build here, but containerising on top of it is an extra step.

**Comment by marticols** [comment]
As a temporal solution, I'm using the project image as a base for the Jedi LSP image.  This way, I don't have to worry about how the project handles dependencies. 

https://github.com/marticols/nvim_lsp_dockerfiles/blob/8180bb89ff0cc890c1554a047ce321901c290cc9/jedi/Dockerfile#L1-L7

In case my project has an image called to_do_app, I generate the project LSP image with:

`make build/jedi tag=to_do_lsp base=to_do_app`

Then I configure lspconfig to use the project LSP image if I'm working on the project directory. 

https://github.com/marticols/dotfiles/blob/9d3dc5df84c962318339689bc360e44464bc377d/nvim/lua/setup/lsp.lua#L15-L40

I also have a fallback jedi lsp image in case I haven't configured the project:

`make build/jedi tag=jedi_lsp base=python:slim-buster`

Maybe giving the option to change the base image and building it before running the image could be a nice solution for this PR.

**Comment by erikreinert** [comment]
This might actually be the only real way this can be solved in a Docker focused approach. Normally - we add our dependencies to the Dockerfile itself during build so this isn't an issue. When trying to add packages at a more global level with Docker post-build is always an issue. This is something we may need to think about "how" we would implement this.

**Comment by erikreinert** [comment]
Another note (though I'd rather not have to do this) would be to accept that this type of language server that requires global packages different from the workspace might not fit the design of `lspcontainers`. I'm not saying that's the case at the moment - I'm just putting it out there as a possibility of limitation due to the design.

**Comment by WhyNotHugo** [comment]
> As a temporal solution, I'm using the project image as a base for the Jedi LSP image. This way, I don't have to worry about how the project handles dependencies.

Most python projects (I'd say over 90%) don't have an accompanying Dockerfile or docker image. This does serve as a workaround for the few large projects that do, but doesn't really scale beyond those few.

An alternative would be to try and install the project using PEP517 tooling (this should at least bring in all runtime dependencies), but that won't work for projects that aren't python libraries (e.g.: desktop applications that ship via meson).

**Comment by WhyNotHugo** [comment]
I'm not using this language server any more. If someone else is interested, feel free to pick it up.

**Pull request closed without merging**
